### ISSUE TITLE
(close context) doesnt work with JeroMQ

### ISSUE THREAD

**Issue by kul** [zeromq/cljzmq#22]
I think we just need another multimethod. 

``` clojure
(defmethod close org.zeromq.ZMQ$Context
  [^org.zeromq.ZMQ$Context zctx]
  (.term zctx))
```

Although i am little confused why doesnt cljzmq's context match with JeroMQ's ZContext.

**Comment by claj** [comment]
It looks like `(.term (.getContext ctx))` works when using JeroMQ.
